spring:
  datasource:
    username: spot
    password: spot
    url: jdbc:mysql://localhost:3306/spot?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver